### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by timh5** [oyvind72/connection-openvz#1]
hi, can you leave a comment here on the basics of how to use this plugin. 
- i assume i copy this into ~/.ansible/plugins/connection_plugins
- how to i specify a specific host in my inventory to use this connection?... 
  - is it the "trasnport" option? do i just set: "transport: openvz"
- how do i specify the vzID to use for that particular host?

for example i can execute a command on VE 25 from ssh here:

ssh root@mainbox.com vzctl enter 25 "runCommand.sh"

but how is this done in ansible?

thanks.

**Comment by oyvind72** [comment]
This is a connection plugin. Use ansible -c option, or "connection:" in playbooks. You need to set a hostname on the container. Use hostnames in your inventory. The plugin will map the hostname to VEID.

You can do "ansible <hostpattern> -i inventoryfile -c openvz -m command -a runCommand.sh"

**Comment by bactisme** [comment]
I just dropped connection_plugin dir  where I am running ansible-playbook, and it's worked.

Also, you can pass connection in the inventory file.

```
[webcommon]
test.humanoid.fr ansible_connection=openvz
```

**Comment by ask0n** [comment]
Is it possible to use it in manner of https://github.com/austinhyde/ansible-sshjail ? 
I.e. use this definition: container_hostname@openvzhost. Because as far I understand ansible must be run on openvzhost itself to manage local containers via this connection plugin?

**Comment by oyvind72** [comment]
This connection plugin is only for managing local containers. When I manage a remote container, I usually have opensshd running in it and connect to it as regular hosts.

**Comment by ask0n** [comment]
Unfortunally I'm not python guru, but I think it wold be great for ansible community to get openvz connection plugin, which could work as sshjail plugin. FreeBSD jails are very similar to vz containers, could you please add sshjail functional to your plugin?

**Comment by oyvind72** [comment]
This is beyond the scope of this plugin. Perhaps its a good idea for someone to fork this and extend the functionality.

**Comment by ask0n** [comment]
Ok, anyway, thank you! )
