### ISSUE TITLE
Ansible 1.9 changes

### ISSUE THREAD

**Issue by bactisme** [oyvind72/connection-openvz#2]
**The Ansible API for connection plugins change a bit with Ansible 1.9**

The plugin must be updated, if not it crash with the error : **TypeError: exec_command() got an unexpected keyword argument 'become_user'**

Line 37, 

```
def exec_command(self,cmd,tmp_path,sudo_user=None,sudoable=False,executable='/bin/sh',in_data=None,su=None,su_user=None):
```

becomes : 

```
def exec_command(self,cmd,tmp_path,sudo_user=None,become_user=None,sudoable=False,executable='/bin/sh',in_data=None,su=None,su_user=None):
```

(note the "become_user=None," )

**Comment by oyvind72** [comment]
Thanks. I have updated the plugin.
